compute_RGB – ForColormap
compute_RGB Subroutine
MIT
11 statements
Source File
private pure subroutine compute_RGB(self, z, red, green, blue)
Most of the time you will just give z to obtain RGB values:
Type Bound
Colormap
Arguments
Type Intent Optional Attributes Name
class(Colormap), intent(inout) :: self
real(kind=wp), intent(in) :: z
integer, intent(out) :: red
integer, intent(out) :: green
integer, intent(out) :: blue
Calls
Called by
Call graph
compute_rgb calls get_rgb
test_colormap calls compute_rgb
write_ppm_colorbar calls compute_rgb
check calls compute_rgb
create calls write_ppm_colorbar
demo calls test_colormap, write_ppm_colorbar
demo_reverse calls test_colormap, write_ppm_colorbar
example1 calls test_colormap, write_ppm_colorbar
extract calls write_ppm_colorbar
modify calls write_ppm_colorbar