create_lagrange – ForColormap
create_lagrange Subroutine
MIT
23 statements
Source File
private pure subroutine create_lagrange(self, name, zmin, zmax, colors, levels, reverse)
You can create a custom colormap using Lagrange interpolation:
Type Bound
Colormap
Arguments
Type Intent Optional Attributes Name
class(Colormap), intent(inout) :: self
character(len=*), intent(in) :: name
real(kind=wp), intent(in) :: zmin
real(kind=wp), intent(in) :: zmax
integer, intent(in), dimension(:, :) :: colors
integer, intent(in) :: levels
logical, intent(in), optional :: reverse
Calls
Called by
Call graph
create_lagrange calls check, lagrange, reverse
check calls get_levels, get_name, get_ncolormaps, set_all
lagrange calls lagrange_poly
set_all calls set_info
create calls create_lagrange