create_bezier – ForColormap
create_bezier Subroutine
MIT
23 statements
Source File
private pure subroutine create_bezier(self, name, zmin, zmax, colors, levels, reverse)
You can create a custom colormap using Bezier interpolation:
Type Bound
Colormap
Arguments
Type Intent Optional Attributes Name
class(Colormap), intent(inout) :: self
character(len=*), intent(in) :: name
real(kind=wp), intent(in) :: zmin
real(kind=wp), intent(in) :: zmax
integer, intent(in), dimension(:, :) :: colors
integer, intent(in) :: levels
logical, intent(in), optional :: reverse
Calls
Called by
Call graph
create_bezier calls bezier, check, reverse
bezier calls factorial
check calls get_levels, get_name, get_ncolormaps, set_all
set_all calls set_info
create calls create_bezier