deallocate_table – ForColormap
deallocate_table Subroutine
MIT
12 statements
Source File
private pure elemental subroutine deallocate_table(this)
Type Bound
table
Arguments
Type Intent Optional Attributes Name
class(table), intent(inout) :: this
Called by
Source Code
   pure elemental subroutine deallocate_table(this)
      class(table), intent(inout) :: this
      if (allocated(this%name)) deallocate(this%name)
      if (allocated(this%family)) deallocate(this%family)
      if (allocated(this%gradient)) deallocate(this%gradient)
      if (allocated(this%palette)) deallocate(this%palette)
      if (allocated(this%colorbar)) deallocate(this%colorbar)
      if (allocated(this%package)) deallocate(this%package)
      if (allocated(this%author)) deallocate(this%author)
      if (allocated(this%license)) deallocate(this%license)
      if (allocated(this%url)) deallocate(this%url)
   end subroutine deallocate_table
Call graph
deallocate_colormaps_info calls deallocate_table
colormaps_list calls deallocate_colormaps_info
write_info calls deallocate_colormaps_info