get_RGB – ForColormap
get_RGB Subroutine
MIT
8 statements
Source File
private pure subroutine get_RGB(self, level, red, green, blue)
But you can also obtain RGB by giving directly a level number:
Type Bound
Colormap
Arguments
Type Intent Optional Attributes Name
class(Colormap), intent(inout) :: self
integer, intent(in) :: level
integer, intent(out) :: red
integer, intent(out) :: green
integer, intent(out) :: blue
Called by
Call graph
compute_rgb calls get_rgb
check calls get_rgb, compute_rgb
test_colormap calls compute_rgb
write_ppm_colorbar calls compute_rgb
create calls write_ppm_colorbar
demo calls test_colormap, write_ppm_colorbar
demo_reverse calls test_colormap, write_ppm_colorbar
example1 calls test_colormap, write_ppm_colorbar
extract calls write_ppm_colorbar
modify calls write_ppm_colorbar