get_ncolormaps – ForColormap
get_ncolormaps Function
MIT
5 statements
Source File
private pure elemental function get_ncolormaps(this) result(ncolormaps)
Type Bound
Colormaps_info
Arguments
Type Intent Optional Attributes Name
class(Colormaps_info), intent(in) :: this
Return Value integer
Called by
Source Code
   pure elemental function get_ncolormaps(this) result(ncolormaps)
      class(Colormaps_info), intent(in) :: this
      integer :: ncolormaps
      ncolormaps = size(this%colormaps)
   end function get_ncolormaps
Call graph
check calls get_ncolormaps
write calls get_ncolormaps
create calls check, create_bezier, create_lagrange
create_bezier calls check
create_lagrange calls check
load calls check
set calls check, create
extract calls create, set, extract
demo calls create, load, set
demo_reverse calls create, load, set
example1 calls load
modify calls set