get_levels – ForColormap
get_levels Function
MIT
6 statements
Source File
private pure function get_levels(this, index) result(levels)
Type Bound
Colormaps_info
Arguments
Type Intent Optional Attributes Name
class(Colormaps_info), intent(in) :: this
integer, intent(in) :: index
Return Value integer
Called by
Source Code
   pure function get_levels(this, index) result(levels)
      class(Colormaps_info), intent(in) :: this
      integer, intent(in) :: index
      integer :: levels
      levels = this%colormaps(index)%levels
   end function get_levels
Call graph
check calls get_levels, create, set
create calls check, create_bezier, create_lagrange
create_bezier calls check
create_lagrange calls check
load calls check
set calls check, create
extract calls create, set, extract
demo calls create, load, set
demo_reverse calls create, load, set
example1 calls load
modify calls set