get_zmax – ForColormap
get_zmax Function
MIT
5 statements
Source File
private pure function get_zmax(self) result(zmax)
Type Bound
Colormap
Arguments
Type Intent Optional Attributes Name
class(Colormap), intent(in) :: self
Return Value real(kind=wp)
Called by
Call graph
write_ppm_colorbar calls get_zmax
check calls get_zmax
create calls write_ppm_colorbar
demo calls write_ppm_colorbar
demo_reverse calls write_ppm_colorbar
example1 calls write_ppm_colorbar
extract calls write_ppm_colorbar
modify calls write_ppm_colorbar