get_name – ForColormap
get_name Function
MIT
6 statements
Source File
private pure elemental function get_name(this, index) result(name)
Type Bound
Colormaps_info
Arguments
Type Intent Optional Attributes Name
class(Colormaps_info), intent(in) :: this
integer, intent(in) :: index
Return Value character(len=colormap_name_length)
Called by
Source Code
   pure elemental function get_name(this, index) result(name)
      class(Colormaps_info), intent(in) :: this
      integer, intent(in) :: index
      character(colormap_name_length) :: name
      name = trim(this%colormaps(index)%name)
   end function get_name
Call graph
check calls get_name
create calls check, create_bezier, create_lagrange
create_bezier calls check
create_lagrange calls check
load calls check
set calls check, create
extract calls create, set, extract
demo calls create, load, set
demo_reverse calls create, load, set
example1 calls load
modify calls set