reverse – ForColormap
reverse Subroutine
MIT
10 statements
Source File
private pure subroutine reverse(self, name)
Reverse the colormap
Type Bound
Colormap
Arguments
Type Intent Optional Attributes Name
class(Colormap), intent(inout) :: self
character(len=*), intent(in), optional :: name
Called by
Source Code
    pure subroutine reverse(self, name)
        class(Colormap), intent(inout) :: self
        character(*), intent(in), optional :: name
        self%map(:,:) = self%map(size(self%map,1)-1:0:-1, :)
        if (present(name)) then
            self%name = trim(name)
        else
            self%name = trim(self%name)//'_reverse'
        end if
    end subroutine reverse
Call graph
create calls reverse, create_bezier, create_lagrange
create_bezier calls reverse
create_lagrange calls reverse
extract calls reverse, create, extract, set
load calls reverse
set calls reverse, create
check calls create, set
demo calls create, load, set
demo_reverse calls create, load, set
example1 calls load
modify calls set