set_info – ForColormap
set_info Subroutine
MIT
15 statements
Source File
private pure elemental subroutine set_info(this, package, family, name, gradient, palette, author, license, url, colorbar, levels)
Set information about the colormap
Type Bound
table
Arguments
Type Intent Optional Attributes Name
class(table), intent(inout) :: this
character(len=*), intent(in) :: package
character(len=*), intent(in) :: family
character(len=*), intent(in) :: name
character(len=*), intent(in) :: gradient
character(len=*), intent(in) :: palette
character(len=*), intent(in) :: author
character(len=*), intent(in) :: license
character(len=*), intent(in) :: url
character(len=*), intent(in) :: colorbar
integer, intent(in) :: levels
Called by
Source Code
   pure elemental subroutine set_info(this, package, family, name, gradient, palette, author, license, url, colorbar, levels)
      class(table), intent(inout) :: this
      character(*), intent(in) :: package, family, name, gradient, palette, author, license, url, colorbar
      integer, intent(in) :: levels
      allocate(this%package, source=trim(package))
      allocate(this%family, source=trim(family))
      allocate(this%name, source=trim(name))
      allocate(this%gradient, source=trim(gradient))
      allocate(this%palette, source=trim(palette))
      allocate(this%author, source=trim(author))
      allocate(this%license, source=trim(license))
      allocate(this%url, source=trim(url))
      allocate(this%colorbar, source=trim(colorbar))
      this%levels = levels
   end subroutine set_info
Call graph
set_all calls set_info
check calls set_all, create, set
colormaps_list calls set_all
write_info calls set_all
create calls check, create_bezier, create_lagrange
create_bezier calls check
create_lagrange calls check
load calls check
set calls check, create
extract calls create, set, extract
demo calls create, load, set
demo_reverse calls create, load, set
example1 calls load
modify calls set