set_all – ForColormap
set_all Subroutine
MIT
468 statements
Source File
private pure elemental subroutine set_all(this)
Set information for all colormaps.
Type Bound
Colormaps_info
Arguments
Type Intent Optional Attributes Name
class(Colormaps_info), intent(inout) :: this
Calls
Called by
Source Code
   pure elemental subroutine set_all(this)
      class(Colormaps_info), intent(inout) :: this
      integer :: i
      i = 1
      call this%colormaps(i)%set_info(&
         name       = "acton",&
         family     = "acton",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "acton_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "acton10",&
         family     = "acton",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "acton10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "acton25",&
         family     = "acton",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "acton25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "acton50",&
         family     = "acton",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "acton50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "acton100",&
         family     = "acton",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "acton100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "actonS",&
         family     = "acton",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "actonS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bam",&
         family     = "bam",&
         gradient   = "Diverging",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "bam_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bam10",&
         family     = "bam",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "bam10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bam100",&
         family     = "bam",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "bam100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bam25",&
         family     = "bam",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "bam25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bam50",&
         family     = "bam",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "bam50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bamako",&
         family     = "bamako",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "bamako_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bamako10",&
         family     = "bamako",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "bamako10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bamako100",&
         family     = "bamako",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "bamako100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bamako25",&
         family     = "bamako",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "bamako25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bamako50",&
         family     = "bamako",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "bamako50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bamakoS",&
         family     = "bamako",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "bamakoS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bamO",&
         family     = "bam",&
         gradient   = "Cyclic",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "bamO_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bamO10",&
         family     = "bam",&
         gradient   = "Cyclic",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "bamO10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bamO100",&
         family     = "bam",&
         gradient   = "Cyclic",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "bamO100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bamO25",&
         family     = "bam",&
         gradient   = "Cyclic",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "bamO25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bamO50",&
         family     = "bam",&
         gradient   = "Cyclic",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "bamO50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlow",&
         family     = "batlow",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "batlow_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlow10",&
         family     = "batlow",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "batlow10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlow100",&
         family     = "batlow",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "batlow100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlow25",&
         family     = "batlow",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "batlow25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlow50",&
         family     = "batlow",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "batlow50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlowK",&
         family     = "batlow",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "batlowK_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlowK10",&
         family     = "batlow",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "batlowK10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlowK100",&
         family     = "batlow",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "batlowK100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlowK25",&
         family     = "batlow",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "batlowK25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlowK50",&
         family     = "batlow",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "batlowK50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlowKS",&
         family     = "batlow",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "batlowKS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlowS",&
         family     = "batlow",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "batlowS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlowW",&
         family     = "batlow",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "batlowW_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlowW10",&
         family     = "batlow",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "batlowW10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlowW100",&
         family     = "batlow",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "batlowW100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlowW25",&
         family     = "batlow",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "batlowW25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlowW50",&
         family     = "batlow",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "batlowW50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "batlowWS",&
         family     = "batlow",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "batlowWS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "berlin",&
         family     = "berlin",&
         gradient   = "Diverging",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "berlin_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "berlin10",&
         family     = "berlin",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "berlin10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "berlin100",&
         family     = "berlin",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "berlin100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "berlin25",&
         family     = "berlin",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "berlin25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "berlin50",&
         family     = "berlin",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "berlin50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bilbao",&
         family     = "bilbao",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "bilbao_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bilbao10",&
         family     = "bilbao",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "bilbao10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bilbao100",&
         family     = "bilbao",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "bilbao100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bilbao25",&
         family     = "bilbao",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "bilbao25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bilbao50",&
         family     = "bilbao",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "bilbao50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bilbaoS",&
         family     = "bilbao",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "bilbaoS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "broc",&
         family     = "broc",&
         gradient   = "Diverging",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "broc_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "broc10",&
         family     = "broc",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "broc10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "broc100",&
         family     = "broc",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "broc100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "broc25",&
         family     = "broc",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "broc25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "broc50",&
         family     = "broc",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "broc50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "brocO",&
         family     = "broc",&
         gradient   = "Cyclic",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "brocO_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "brocO10",&
         family     = "broc",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "brocO10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "brocO100",&
         family     = "broc",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "brocO100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "brocO25",&
         family     = "broc",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "brocO25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "brocO50",&
         family     = "broc",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "brocO50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "buda",&
         family     = "buda",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "buda_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "buda10",&
         family     = "buda",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "buda10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "buda100",&
         family     = "buda",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "buda100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "buda25",&
         family     = "buda",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "buda25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "buda50",&
         family     = "buda",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "buda50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "budaS",&
         family     = "buda",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "budaS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bukavu",&
         family     = "bukavu",&
         gradient   = "Multi-Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "bukavu_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bukavu10",&
         family     = "bukavu",&
         gradient   = "Multi-Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "bukavu10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bukavu100",&
         family     = "bukavu",&
         gradient   = "Multi-Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "bukavu100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bukavu25",&
         family     = "bukavu",&
         gradient   = "Multi-Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "bukavu25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "bukavu50",&
         family     = "bukavu",&
         gradient   = "Multi-Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "bukavu50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "cork",&
         family     = "cork",&
         gradient   = "Diverging",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "cork_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "cork10",&
         family     = "cork",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "cork10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "cork100",&
         family     = "cork",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "cork100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "cork25",&
         family     = "cork",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "cork25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "cork50",&
         family     = "cork",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "cork50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "corkO",&
         family     = "cork",&
         gradient   = "Cyclic",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "corkO_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "corkO10",&
         family     = "cork",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "corkO10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "corkO100",&
         family     = "cork",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "corkO100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "corkO25",&
         family     = "cork",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "corkO25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "corkO50",&
         family     = "cork",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "corkO50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "davos",&
         family     = "davos",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "davos_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "davos10",&
         family     = "davos",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "davos10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "davos100",&
         family     = "davos",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "davos100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "davos25",&
         family     = "davos",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "davos25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "davos50",&
         family     = "davos",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "davos50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "davosS",&
         family     = "davos",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "davosS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "devon",&
         family     = "devon",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "devon_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "devon10",&
         family     = "devon",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "devon10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "devon100",&
         family     = "devon",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "devon100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "devon25",&
         family     = "devon",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "devon25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "devon50",&
         family     = "devon",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "devon50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "devonS",&
         family     = "devon",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "devonS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "fes",&
         family     = "fes",&
         gradient   = "Multi-Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "fes_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "fes10",&
         family     = "fes",&
         gradient   = "Multi-Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "fes10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "fes100",&
         family     = "fes",&
         gradient   = "Multi-Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "fes100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "fes25",&
         family     = "fes",&
         gradient   = "Multi-Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "fes25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "fes50",&
         family     = "fes",&
         gradient   = "Multi-Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "fes50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "glasgow",&
         family     = "glasgow",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "glasgow_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "glasgow10",&
         family     = "glasgow",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "glasgow10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "glasgow100",&
         family     = "glasgow",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "glasgow100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "glasgow25",&
         family     = "glasgow",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "glasgow25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "glasgow50",&
         family     = "glasgow",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "glasgow50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "glasgowS",&
         family     = "glasgow",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "glasgowS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "grayC",&
         family     = "grayC",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "grayC_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "grayC10",&
         family     = "grayC",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "grayC10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "grayC100",&
         family     = "grayC",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "grayC100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "grayC25",&
         family     = "grayC",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "grayC25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "grayC50",&
         family     = "grayC",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "grayC50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "grayCS",&
         family     = "grayC",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "grayCS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "hawaii",&
         family     = "hawaii",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "hawaii_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "hawaii10",&
         family     = "hawaii",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "hawaii10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "hawaii100",&
         family     = "hawaii",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "hawaii100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "hawaii25",&
         family     = "hawaii",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "hawaii25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "hawaii50",&
         family     = "hawaii",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "hawaii50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "hawaiiS",&
         family     = "hawaii",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "hawaiiS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "imola",&
         family     = "imola",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "imola_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "imola10",&
         family     = "imola",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "imola10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "imola100",&
         family     = "imola",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "imola100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "imola25",&
         family     = "imola",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "imola25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "imola50",&
         family     = "imola",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "imola50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "imolaS",&
         family     = "imola",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "imolaS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lajolla",&
         family     = "lajolla",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "lajolla_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lajolla10",&
         family     = "lajolla",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "lajolla10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lajolla100",&
         family     = "lajolla",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "lajolla100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lajolla25",&
         family     = "lajolla",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "lajolla25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lajolla50",&
         family     = "lajolla",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "lajolla50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lajollaS",&
         family     = "lajolla",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "lajollaS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lapaz",&
         family     = "lapaz",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "lapaz_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lapaz10",&
         family     = "lapaz",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "lapaz10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lapaz100",&
         family     = "lapaz",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "lapaz100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lapaz25",&
         family     = "lapaz",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "lapaz25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lapaz50",&
         family     = "lapaz",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "lapaz50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lapazS",&
         family     = "lapaz",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "lapazS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lipariS",&
         family     = "lipari",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "lipariS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lipari",&
         family     = "lipari",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "lipari_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lipari10",&
         family     = "lipari",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "lipari10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lipari100",&
         family     = "lipari",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "lipari100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lipari25",&
         family     = "lipari",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "lipari25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lipari50",&
         family     = "lipari",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "lipari50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lisbon",&
         family     = "lisbon",&
         gradient   = "Diverging",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "lisbon_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lisbon10",&
         family     = "lisbon",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "lisbon10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lisbon100",&
         family     = "lisbon",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "lisbon100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lisbon25",&
         family     = "lisbon",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "lisbon25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info(&
         name       = "lisbon50",&
         family     = "lisbon",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "lisbon50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "managua",&
         family     = "managua",&
         gradient   = "Diverging",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "managua_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "managua10",&
         family     = "managua",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "managua10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "managua100",&
         family     = "managua",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "managua100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "managua25",&
         family     = "managua",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "managua25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "managua50",&
         family     = "managua",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "managua50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "navia",&
         family     = "navia",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "navia_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "navia10",&
         family     = "navia",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "navia10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "navia100",&
         family     = "navia",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "navia100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "navia25",&
         family     = "navia",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "navia25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "navia50",&
         family     = "navia",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "navia50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "naviaS",&
         family     = "navia",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "naviaS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "naviaW",&
         family     = "navia",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "naviaW_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "naviaWS",&
         family     = "navia",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "naviaWS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "naviaW10",&
         family     = "navia",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "naviaW10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "naviaW100",&
         family     = "navia",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "naviaW100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "naviaW25",&
         family     = "navia",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "naviaW25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "naviaW50",&
         family     = "navia",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "naviaW50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "nuuk",&
         family     = "nuuk",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "nuuk_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "nuuk10",&
         family     = "nuuk",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "nuuk10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "nuuk100",&
         family     = "nuuk",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "nuuk100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "nuuk25",&
         family     = "nuuk",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "nuuk25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "nuuk50",&
         family     = "nuuk",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "nuuk50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "nuukS",&
         family     = "nuuk",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "nuukS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "oleron",&
         family     = "oleron",&
         gradient   = "Multi-Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "oleron_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "oleron10",&
         family     = "oleron",&
         gradient   = "Multi-Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "oleron10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "oleron100",&
         family     = "oleron",&
         gradient   = "Multi-Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "oleron100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "oleron25",&
         family     = "oleron",&
         gradient   = "Multi-Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "oleron25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "oleron50",&
         family     = "oleron",&
         gradient   = "Multi-Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "oleron50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "oslo",&
         family     = "oslo",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "oslo_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "oslo10",&
         family     = "oslo",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "oslo10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "oslo100",&
         family     = "oslo",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "oslo100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "oslo25",&
         family     = "oslo",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "oslo25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "oslo50",&
         family     = "oslo",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "oslo50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "osloS",&
         family     = "oslo",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "osloS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "roma",&
         family     = "roma",&
         gradient   = "Diverging",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "roma_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "roma10",&
         family     = "roma",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "roma10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "roma100",&
         family     = "roma",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "roma100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "roma25",&
         family     = "roma",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "roma25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "roma50",&
         family     = "roma",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "roma50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "romaO",&
         family     = "roma",&
         gradient   = "Cyclic",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "romaO_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "romaO10",&
         family     = "roma",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "romaO10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "romaO100",&
         family     = "roma",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "romaO100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "romaO25",&
         family     = "roma",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "romaO25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "romaO50",&
         family     = "roma",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "romaO50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "tofino",&
         family     = "tofino",&
         gradient   = "Diverging",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "tofino_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "tofino10",&
         family     = "tofino",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "tofino10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "tofino100",&
         family     = "tofino",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "tofino100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "tofino25",&
         family     = "tofino",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "tofino25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "tofino50",&
         family     = "tofino",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "tofino50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "tokyo",&
         family     = "tokyo",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "tokyo_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "tokyo10",&
         family     = "tokyo",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "tokyo10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "tokyo100",&
         family     = "tokyo",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "tokyo100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "tokyo25",&
         family     = "tokyo",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "tokyo25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "tokyo50",&
         family     = "tokyo",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "tokyo50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "tokyoS",&
         family     = "tokyo",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "tokyoS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "turku",&
         family     = "turku",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "turku_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "turku10",&
         family     = "turku",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "turku10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "turku100",&
         family     = "turku",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "turku100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "turku25",&
         family     = "turku",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "turku25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "turku50",&
         family     = "turku",&
         gradient   = "Sequential",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "turku50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "turkuS",&
         family     = "turku",&
         gradient   = "Categorical",&
         palette    = "Continuous",&
         levels     = 100, &
         colorbar   = "turkuS_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "vanimo",&
         family     = "vanimo",&
         gradient   = "Diverging",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "vanimo_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "vanimo10",&
         family     = "vanimo",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "vanimo10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "vanimo100",&
         family     = "vanimo",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "vanimo100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "vanimo25",&
         family     = "vanimo",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "vanimo25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "vanimo50",&
         family     = "vanimo",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "vanimo50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "vik",&
         family     = "vik",&
         gradient   = "Diverging",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "vik_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "vik10",&
         family     = "vik",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "vik10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "vik100",&
         family     = "vik",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "vik100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "vik25",&
         family     = "vik",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "vik25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "vik50",&
         family     = "vik",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "vik50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "vikO",&
         family     = "vik",&
         gradient   = "Cyclic",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "vikO_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "vikO10",&
         family     = "vik",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 10, &
         colorbar   = "vikO10_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "vikO100",&
         family     = "vik",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 100, &
         colorbar   = "vikO100_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "vikO25",&
         family     = "vik",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 25, &
         colorbar   = "vikO25_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "vikO50",&
         family     = "vik",&
         gradient   = "Diverging",&
         palette    = "Discrete",&
         levels     = 50, &
         colorbar   = "vikO50_colorbar.ppm",&
         package    = "Scientific Colour Map",&
         author     = "Fabio Crameri",&
         license    = "MIT license",&
         url        = "https://www.fabiocrameri.ch")
      ! Miscellaneous colormaps:
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "black_body",&
         family     = "black_body",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 1024, &
         colorbar   = "black_body_colorbar.ppm",&
         package    = "Miscellaneous",&
         author     = "Kenneth Moreland",&
         license    = "Public Domain (CC0)",&
         url        = "https://www.kennethmoreland.com")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "cubehelix",&
         family     = "cubehelix",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = -1, & ! -1 means that the number of levels is not fixed
         colorbar   = "cubehelix_colorbar.ppm",&
         package    = "Miscellaneous",&
         author     = "Dave Green",&
         license    = "Public Domain (Unlicense license)",&
         url        = "https://people.phy.cam.ac.uk/dag9/CUBEHELIX")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "fire",&
         family     = "fire",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = -1, & ! -1 means that the number of levels is not fixed
         colorbar   = "fire_colorbar.ppm",&
         package    = "Miscellaneous",&
         author     = "Vincent Magnin",&
         license    = "Public Domain (CC0)",&
         url        = "")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "rainbow",&
         family     = "rainbow",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "rainbow_colorbar.ppm",&
         package    = "Miscellaneous",&
         author     = "Vincent Magnin",&
         license    = "Public Domain (CC0)",&
         url        = "")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "inv_rainbow",&
         family     = "rainbow",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "inv_rainbow_colorbar.ppm",&
         package    = "Miscellaneous",&
         author     = "Vincent Magnin",&
         license    = "Public Domain (CC0)",&
         url        = "")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "zebra",&
         family     = "zebra",&
         gradient   = "Categorical",&
         palette    = "Discrete",&
         levels     = 256, &
         colorbar   = "zebra_colorbar.ppm",&
         package    = "Miscellaneous",&
         author     = "Vincent Magnin",&
         license    = "Public Domain (CC0)",&
         url        = "")
      ! Matplotlib colormaps:
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "magma",&
         family     = "magma",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "magma_colorbar.ppm",&
         package    = "Matplotlib",&
         author     = "N. Smith et al.",&
         license    = "Public Domain (CC0)",&
         url        = "https://bids.github.io/colormap/")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "inferno",&
         family     = "inferno",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "inferno_colorbar.ppm",&
         package    = "Matplotlib",&
         author     = "N. Smith et al.",&
         license    = "Public Domain (CC0)",&
         url        = "https://bids.github.io/colormap/")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "plasma",&
         family     = "plasma",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "plasma_colorbar.ppm",&
         package    = "Matplotlib",&
         author     = "N. Smith et al.",&
         license    = "Public Domain (CC0)",&
         url        = "https://bids.github.io/colormap/")
      i = i + 1
      call this%colormaps(i)%set_info( &
         name       = "viridis",&
         family     = "viridis",&
         gradient   = "Sequential",&
         palette    = "Continuous",&
         levels     = 256, &
         colorbar   = "viridis_colorbar.ppm",&
         package    = "Matplotlib",&
         author     = "N. Smith et al.",&
         license    = "Public Domain (CC0)",&
         url        = "https://bids.github.io/colormap/")
   end subroutine set_all
Call graph
set_all calls set_info
check calls set_all, create, set
colormaps_list calls set_all
write_info calls set_all
create calls check, create_bezier, create_lagrange
create_bezier calls check
create_lagrange calls check
load calls check
set calls check, create
extract calls create, set, extract
demo calls create, load, set
demo_reverse calls create, load, set
example1 calls load
modify calls set