test_colormap – ForColormap
test_colormap Subroutine
MIT
25 statements
Source File
subroutine test_colormap(self, filename, encoding)
Uses
forimage
Arguments
Type Intent Optional Attributes Name
type(Colormap), intent(inout) :: self
character(len=*), intent(in) :: filename
character(len=*), intent(in) :: encoding
Calls
Called by
Source Code
    subroutine test_colormap(self, filename, encoding)
        use forimage, only: format_pnm
        type(Colormap), intent(inout) :: self
        character(*), intent(in) :: filename
        integer :: k, j     ! Pixbuffer coordinates
        integer, parameter :: pixwidth  = 600
        integer, parameter :: pixheight = 600
        integer, dimension(:,:), allocatable :: rgb_image
        integer  :: red, green, blue
        real(wp) :: z
        type(format_pnm) :: ppm
        character(*), intent(in) :: encoding
        allocate(rgb_image(pixheight,pixwidth*3))
        do k = 0, pixwidth-1
            do j = 0, pixheight-1
                ! Computing a z=f(x,y) function:
                z = 1.0_wp + sin(k*j/10000.0_wp) * cos(j/100.0_wp)
                ! The corresponding RGB values in our colormap:
                call self%compute_RGB(z, red, green, blue)
                rgb_image(pixheight-j, 3*(k+1)-2) = red
                rgb_image(pixheight-j, 3*(k+1)-1) = green
                rgb_image(pixheight-j, 3*(k+1))   = blue
            end do
        end do
        call ppm%set_pnm(encoding    = encoding,&
                        file_format = 'ppm',&
                        width       = pixwidth,&
                        height      = pixheight,&
                        max_color   = 255,&
                        comment     = 'comment',&
                        pixels      = rgb_image)
        call ppm%export_pnm(filename)
    end subroutine test_colormap
Call graph
test_colormap calls export_pnm, compute_rgb, set_pnm
compute_rgb calls get_rgb
example1 calls test_colormap