zebra_colormap – ForColormap
zebra_colormap Subroutine
MIT
11 statements
Source File
public pure subroutine zebra_colormap(map)
Arguments
Type Intent Optional Attributes Name
integer, intent(out), dimension(:,:), allocatable :: map
Called by
Source Code
    pure subroutine zebra_colormap(map)
        integer, dimension(:,:), allocatable, intent(out) :: map
        integer :: levels, last, i
        ! The user can not choose the number of levels:
        levels = 256
        last = levels - 1
        allocate(map(0:last, 1:3))
        ! Black and white zebras:
        do i = 0, 224, 32
            map(i   :i+15, :) = 0
            map(i+16:i+31, :) = 255
        end do
    end subroutine zebra_colormap
Call graph
set calls zebra_colormap
check calls set
demo calls set
demo_reverse calls set
extract calls set
modify calls set