        ! Scientific colour maps collection (Fabio Crameri):
        case("acton")
            call self%create("acton",  self%zmin, self%zmax, acton)
        case("actonS")
            call self%create("actonS",  self%zmin, self%zmax, actonS)
        case("bamako")
            call self%create("bamako",  self%zmin, self%zmax, bamako)
        case("bamakoS")
            call self%create("bamakoS",  self%zmin, self%zmax, bamakoS)
        case("bam")
            call self%create("bam",  self%zmin, self%zmax, bam)
        case("bamO")
            call self%create("bamO",  self%zmin, self%zmax, bamO)
        case("batlowK")
            call self%create("batlowK",  self%zmin, self%zmax, batlowK)
        case("batlowKS")
            call self%create("batlowKS",  self%zmin, self%zmax, batlowKS)
        case("batlow")
            call self%create("batlow",  self%zmin, self%zmax, batlow)
        case("batlowS")
            call self%create("batlowS",  self%zmin, self%zmax, batlowS)
        case("batlowW")
            call self%create("batlowW",  self%zmin, self%zmax, batlowW)
        case("batlowWS")
            call self%create("batlowWS",  self%zmin, self%zmax, batlowWS)
        case("berlin")
            call self%create("berlin",  self%zmin, self%zmax, berlin)
        case("bilbao")
            call self%create("bilbao",  self%zmin, self%zmax, bilbao)
        case("bilbaoS")
            call self%create("bilbaoS",  self%zmin, self%zmax, bilbaoS)
        case("broc")
            call self%create("broc",  self%zmin, self%zmax, broc)
        case("brocO")
            call self%create("brocO",  self%zmin, self%zmax, brocO)
        case("buda")
            call self%create("buda",  self%zmin, self%zmax, buda)
        case("budaS")
            call self%create("budaS",  self%zmin, self%zmax, budaS)
        case("bukavu")
            call self%create("bukavu",  self%zmin, self%zmax, bukavu)
        case("cork")
            call self%create("cork",  self%zmin, self%zmax, cork)
        case("corkO")
            call self%create("corkO",  self%zmin, self%zmax, corkO)
        case("davos")
            call self%create("davos",  self%zmin, self%zmax, davos)
        case("davosS")
            call self%create("davosS",  self%zmin, self%zmax, davosS)
        case("devon")
            call self%create("devon",  self%zmin, self%zmax, devon)
        case("devonS")
            call self%create("devonS",  self%zmin, self%zmax, devonS)
        case("fes")
            call self%create("fes",  self%zmin, self%zmax, fes)
        case("glasgow")
            call self%create("glasgow",  self%zmin, self%zmax, glasgow)
        case("glasgowS")
            call self%create("glasgowS",  self%zmin, self%zmax, glasgowS)
        case("grayC")
            call self%create("grayC",  self%zmin, self%zmax, grayC)
        case("grayCS")
            call self%create("grayCS",  self%zmin, self%zmax, grayCS)
        case("hawaii")
            call self%create("hawaii",  self%zmin, self%zmax, hawaii)
        case("hawaiiS")
            call self%create("hawaiiS",  self%zmin, self%zmax, hawaiiS)
        case("imola")
            call self%create("imola",  self%zmin, self%zmax, imola)
        case("imolaS")
            call self%create("imolaS",  self%zmin, self%zmax, imolaS)
        case("lajolla")
            call self%create("lajolla",  self%zmin, self%zmax, lajolla)
        case("lajollaS")
            call self%create("lajollaS",  self%zmin, self%zmax, lajollaS)
        case("lapaz")
            call self%create("lapaz",  self%zmin, self%zmax, lapaz)
        case("lapazS")
            call self%create("lapazS",  self%zmin, self%zmax, lapazS)
        case("lipari")
            call self%create("lipari",  self%zmin, self%zmax, lipari)
        case("lipariS")
            call self%create("lipariS",  self%zmin, self%zmax, lipariS)
        case("lisbon")
            call self%create("lisbon",  self%zmin, self%zmax, lisbon)
        case("managua")
            call self%create("managua",  self%zmin, self%zmax, managua)
        case("navia")
            call self%create("navia",  self%zmin, self%zmax, navia)
        case("naviaS")
            call self%create("naviaS",  self%zmin, self%zmax, naviaS)
        case("naviaW")
            call self%create("naviaW",  self%zmin, self%zmax, naviaW)
        case("naviaWS")
            call self%create("naviaWS",  self%zmin, self%zmax, naviaWS)
        case("nuuk")
            call self%create("nuuk",  self%zmin, self%zmax, nuuk)
        case("nuukS")
            call self%create("nuukS",  self%zmin, self%zmax, nuukS)
        case("oleron")
            call self%create("oleron",  self%zmin, self%zmax, oleron)
        case("oslo")
            call self%create("oslo",  self%zmin, self%zmax, oslo)
        case("osloS")
            call self%create("osloS",  self%zmin, self%zmax, osloS)
        case("roma")
            call self%create("roma",  self%zmin, self%zmax, roma)
        case("romaO")
            call self%create("romaO",  self%zmin, self%zmax, romaO)
        case("tofino")
            call self%create("tofino",  self%zmin, self%zmax, tofino)
        case("tokyo")
            call self%create("tokyo",  self%zmin, self%zmax, tokyo)
        case("tokyoS")
            call self%create("tokyoS",  self%zmin, self%zmax, tokyoS)
        case("turku")
            call self%create("turku",  self%zmin, self%zmax, turku)
        case("turkuS")
            call self%create("turkuS",  self%zmin, self%zmax, turkuS)
        case("vanimo")
            call self%create("vanimo",  self%zmin, self%zmax, vanimo)
        case("vik")
            call self%create("vik",  self%zmin, self%zmax, vik)
        case("vikO")
            call self%create("vikO",  self%zmin, self%zmax, vikO)
