colormaps_list – ForColormap
colormaps_list Program
MIT
12 statements
Source File
Uses
forcolormap_info
Write colormap information to a file
Calls
Variables
Type Attributes Name Initial
type(Colormaps_info) :: info
Source Code
program colormaps_list
    use forcolormap_info, only: Colormaps_info
    implicit none
    type(Colormaps_info) :: info
    ! Set all colormap information
    call info%set_all()
    !! Write colormap information to a file
    call info%write(gradient='Sequential', file_name='colormaps_list/COLORMAPS_LIST_SEQ.md', verbose=4)
    call info%write(gradient='Multi-Sequential', file_name='colormaps_list/COLORMAPS_LIST_MSQ.md', verbose=4)
    call info%write(gradient='Diverging', file_name='colormaps_list/COLORMAPS_LIST_DIV.md', verbose=4)
    call info%write(gradient='Categorical', file_name='colormaps_list/COLORMAPS_LIST_CAT.md', verbose=4)
    call info%write(gradient='Cyclic', file_name='colormaps_list/COLORMAPS_LIST_CYC.md', verbose=4)
    ! Deallocate all colormap information
    call info%finalize()
end program colormaps_list
Call graph
colormaps_list calls deallocate_colormaps_info, set_all
deallocate_colormaps_info calls deallocate_table
set_all calls set_info