create – ForColormap
create Program
MIT
15 statements
Source File
Uses
forcolormap
This example demonstrates creating a custom colormap using methods like create_lagrange() and create_bezier().
Calls
Variables
Type Attributes Name Initial
integer :: colors(3,3)
type(Colormap) :: custom_cmap
Source Code
program create
    use forcolormap, only: Colormap, wp
    implicit none
    type(Colormap) :: custom_cmap
    integer :: colors(3,3)
    ! Define control colors for the colormap.
    colors(1,:) = [255, 0, 0] ! Red
    colors(2,:) = [0, 255, 0] ! Green
    colors(3,:) = [0, 0, 255] ! Blue
    ! Create a custom colormap using Lagrange interpolation.
    call custom_cmap%create_lagrange('custom_lagrange',  0.0_wp, 2.0_wp, colors, 1024)
    call custom_cmap%colorbar('custom_colorbar_lagrange')
    print *, "See the custom_colorbar_lagrange.ppm colorbar"
    ! Create a custom colormap using Bezier interpolation.
    call custom_cmap%create_bezier('custom_bezier',  0.0_wp, 2.0_wp, colors, 1024)
    call custom_cmap%colorbar('custom_colorbar_bezier')
    print *, "See the custom_colorbar_bezier.ppm colorbar"
end program create
Call graph
create calls create_bezier, create_lagrange, write_ppm_colorbar
create_bezier calls bezier, check, reverse
create_lagrange calls check, lagrange, reverse
write_ppm_colorbar calls export_pnm, get_format, compute_rgb, get_zmax, get_zmin, set_format, set_pnm
bezier calls factorial
check calls get_levels, get_name, get_ncolormaps, set_all
compute_rgb calls get_rgb
lagrange calls lagrange_poly
set_all calls set_info