modify – ForColormap
modify Program
MIT
20 statements
Source File
Uses
forcolormap
This example shows how you can modify a colormap with methods like shift(), in concrete cases. In the Scientific colour maps collection, all cyclic colormaps have their bright part in the middle. But we can shift the dark part towards the center. In the Scientific colour maps collection, all categorical colormaps begin with a dark colour, but a shift can be applied to begin with a brighter colour. Two levels towards left Starting from a diverging colormap, we can obtain what could be called a diverging multi-sequential colormap.
Calls
Variables
Type Attributes Name Initial
type(Colormap) :: cmap
Source Code
program modify
    use forcolormap, only: Colormap, wp
    implicit none
    type(Colormap) :: cmap
    !> In the Scientific colour maps collection, all cyclic colormaps have their
    !> bright part in the middle. But we can shift the dark part towards the
    !> center.
    call cmap%set("bamO", 0.0_wp, 2.0_wp)
    call cmap%colorbar("bamO")
    call cmap%shift(cmap%get_levels() / 2)
    call cmap%colorbar("bamO_shifted")
    print *, "See the bamO.ppm and bamO_shifted.ppm colorbars"
    !> In the Scientific colour maps collection, all categorical colormaps
    !> begin with a dark colour, but a shift can be applied to begin with a
    !> brighter colour.
    call cmap%set("actonS", 0.0_wp, 2.0_wp)
    call cmap%colorbar("actonS")
    call cmap%shift(+2)   !! Two levels towards left
    call cmap%colorbar("actonS_shifted")
    print *, "See the actonS.ppm and actonS_shifted.ppm colorbars"
    !> Starting from a diverging colormap, we can obtain what could be called
    !> a diverging multi-sequential colormap.
    call cmap%set("bam", 0.0_wp, 2.0_wp)
    call cmap%colorbar("bam")
    call cmap%shift(cmap%get_levels() / 2)
    call cmap%colorbar("bam_shifted")
    print *, "See the bam.ppm and bam_shifted.ppm colorbars"
end program modify
Call graph
modify calls get_levels, set, shift, write_ppm_colorbar
set calls check, create, cubehelix_colormap, fire_colormap, inv_rainbow_colormap, rainbow_colormap, reverse, zebra_colormap
write_ppm_colorbar calls export_pnm, get_format, compute_rgb, get_zmax, get_zmin, set_format, set_pnm
check calls get_levels, get_name, get_ncolormaps, set_all
compute_rgb calls get_rgb
create calls check, reverse
set_all calls set_info